module: SwiftLintFramework
author: JP Simard
author_url: https://jpsim.com
root_url: https://realm.github.io/SwiftLint/
github_url: https://github.com/realm/SwiftLint
github_file_prefix: https://github.com/realm/SwiftLint/tree/master
swift_build_tool: spm
theme: fullwidth
clean: true
copyright: '© 2020 [JP Simard](https://jpsim.com) under MIT.'

documentation: rule_docs/*.md
# TODO: Upstream support for these settings
# hide_unlisted_documentation: true
# custom_categories_unlisted_prefix: ''
custom_categories:
  - name: Rules
    children:
      - Rule Directory
