module: SwiftLintCore
author: JP Simard, SwiftLint Contributors
author_url: https://jpsim.com
root_url: https://realm.github.io/SwiftLint/
github_url: https://github.com/realm/SwiftLint
github_file_prefix: https://github.com/realm/SwiftLint/tree/main
swift_build_tool: spm
theme: fullwidth
clean: true
copyright: '© 2022 [JP Simard](https://jpsim.com) under MIT.'

documentation: rule_docs/*.md
hide_unlisted_documentation: true
custom_categories_unlisted_prefix: ''
exclude:
  # TODO: Document extensions
  - Source/SwiftLintCore/Extensions/*.swift
custom_categories:
  - name: Rules
    children:
      - Rule Directory
  - name: Reporters
    children:
      - CSVReporter
      - CheckstyleReporter
      - CodeClimateReporter
      - EmojiReporter
      - GitHubActionsLoggingReporter
      - HTMLReporter
      - JSONReporter
      - JUnitReporter
      - MarkdownReporter
