included:
  - Plugins
  - Source
  - Tests
excluded:
  - Tests/SwiftLintFrameworkTests/Resources
analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - all
disabled_rules:
#  - accessibility_label_for_image
#  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
#  - anyobject_protocol
  - balanced_xctest_lifecycle
  - closure_body_length
#  - comma_inheritance
  - conditional_returns_on_newline
  - convenience_type
  - direct_return
#  - discarded_notification_center_observer
#  - discouraged_assert
  - discouraged_optional_boolean
  - discouraged_optional_collection
#  - expiring_todo
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
#  - file_name_no_space
  - file_types_order
  - force_unwrapping
  - function_default_parameter_at_end
#  - ibinspectable_in_extension
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  - legacy_objc_type
  - let_var_whitespace
  - missing_docs
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - no_extension_access_modifier
  - no_grouping_extension
  - no_magic_numbers
#  - nslocalizedstring_require_bundle
  - optional_enum_case_matching
  - prefer_nimble
  - prefer_self_in_static_references
#  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
#  - private_subject
#  - raw_value_for_camel_cased_codable_enum
  - required_deinit
#  - required_enum_case
  - self_binding
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - type_contents_order
  - vertical_whitespace_between_cases
#  - weak_delegate

attributes:
  always_on_line_above:
    - "@OptionGroup"
identifier_name:
  excluded:
    - id
large_tuple: 3
number_separator:
  minimum_length: 5
file_name:
  excluded:
    - SwiftSyntax+SwiftLint.swift
    - GeneratedTests.swift
    - TestHelpers.swift

function_body_length: 60
type_body_length: 400

custom_rules:
  rule_id:
    included: Source/SwiftLintFramework/Rules/.+/\w+\.swift
    name: Rule ID
    message: Rule IDs must be all lowercase, snake case and not end with `rule`
    regex: identifier:\s*("\w+_rule"|"\S*[^a-z_]\S*")
    severity: error
  fatal_error:
    name: Fatal Error
    excluded: "Tests/*"
    message: Prefer using `queuedFatalError` over `fatalError` to avoid leaking compiler host machine paths.
    regex: \bfatalError\b
    match_kinds:
      - identifier
    severity: error
  rule_test_function:
    included: Tests/SwiftLintFrameworkTests/RulesTests.swift
    name: Rule Test Function
    message: Rule Test Function mustn't end with `rule`
    regex: func\s*test\w+(r|R)ule\(\)
    severity: error

unused_import:
  always_keep_imports:
    - SwiftSyntaxBuilder # we can't detect uses of string interpolation of swift syntax nodes
