version: 2
jobs:

  osscheck:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec danger --verbose

  swiftpm_3:
    macos:
      xcode: "8.3.3"
    steps:
      - checkout
      - run: swift test

  swiftpm_4:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: swift test

  xcode_83:
    macos:
      xcode: "8.3.3"
    steps:
      - checkout
      - run: curl -sS https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash
      - run: set -o pipefail && script/cibuild | xcpretty
      - run: echo "3.1.1" > .swift-version; pod lib lint SwiftLintFramework.podspec

  xcode_9:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: curl -sS https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash
      - run: set -o pipefail && script/cibuild | xcpretty
      - run: echo "4.0" > .swift-version; pod lib lint SwiftLintFramework.podspec
      - run: bash <(curl -s https://codecov.io/bash)

  linux_swift_3:
    docker:
      - image: norionomura/sourcekit:311
    steps:
      - checkout
      - run: swift test

  linux_swift_4:
    docker:
      - image: norionomura/swift:40
    steps:
      - checkout
      - run: swift test

workflows:
  version: 2
  workflow:
    jobs:
      - osscheck
      - swiftpm_3
      - swiftpm_4
      - xcode_83
      - xcode_9
      - linux_swift_3
      - linux_swift_4
