version: 2
jobs:

  tsan:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      # Pre-cache
      - run: swift run -Xswiftc -sanitize=thread swiftlint lint --lenient
      # Post-cache
      - run: swift run -Xswiftc -sanitize=thread swiftlint lint --lenient

  osscheck:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec danger --verbose

  swiftpm_4:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: swift test --parallel

  xcode_9:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: set -o pipefail && script/cibuild | xcpretty -r junit
      - store_test_results:
          path: build/reports/
      - run: bash <(curl -s https://codecov.io/bash)

  cocoapods:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: curl -sS https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash
      - run: echo "4.0" > .swift-version; pod lib lint SwiftLintFramework.podspec

  linux_swift_4:
    docker:
      - image: norionomura/swift:40
    steps:
      - checkout
      - run: swift test --parallel

workflows:
  version: 2
  workflow:
    jobs:
      - tsan
      - osscheck
      - swiftpm_4
      - xcode_9
      - cocoapods
      - linux_swift_4
