steps:
  - label: "Bazel"
    commands:
      - echo "+++ Build"
      - bazel build :swiftlint
      - echo "+++ Test"
      - bazel test --test_output=errors //Tests/...
  - label: "SwiftPM"
    commands:
      - echo "+++ Test"
      - swift test --parallel -Xswiftc -DDISABLE_FOCUSED_EXAMPLES
  - label: "Danger"
    commands:
      - echo "--- Build Danger"
      - bazel build //tools:danger
      - echo "+++ Run Danger"
      - ./bazel-bin/tools/danger --verbose
  - label: "TSan Tests"
    commands:
      - echo "+++ Test"
      - bazel test --test_output=streamed --build_tests_only --features=tsan --test_timeout=1000 //Tests/...
  - label: "Sourcery"
    commands:
      - echo "+++ Run Sourcery"
      - make --always-make sourcery
      - echo "+++ Diff Files"
      - git diff --quiet HEAD
