steps:
  # - label: "Bazel"
  #   commands:
  #     - echo "+++ Build"
  #     - bazel build :swiftlint
  #     - echo "+++ Test"
  #     - bazel test --test_output=errors //Tests/...
  # - label: "Danger"
  #   commands:
  #     - echo "--- Bundle Install"
  #     - bundle install
  #     - echo "+++ Run Danger"
  #     - bundle exec danger --verbose
  # - label: "Analyze"
  #   commands:
  #     - echo "+++ Analyze"
  #     - make analyze
  - label: "TSan"
    env:
      DEVELOPER_DIR: /Applications/Xcode-14.0.0-Beta.5.app/Contents/Developer
    commands:
      - bazel clean --expunge
      - echo "+++ Test"
      - bazel test --test_output=streamed --build_tests_only --features=tsan --test_timeout=600 //Tests/...
