steps:
  - label: "Bazel Tests"
    command: bazel test --test_output=errors --test_env IN_PROCESS_SOURCEKIT=1 //Tests/...
  - label: "Danger"
    commands:
      - bundle install
      - bundle exec danger --verbose
  - label: "Analyze"
    command: make analyze
