steps:
  - label: "Bazel"
    commands:
      - echo "+++ Build"
      - bazel build :swiftlint
      - echo "+++ Test"
      - bazel test --test_output=errors //Tests/...
  - label: "SwiftPM"
    commands:
      - echo "+++ Test"
      - swift test --parallel -Xswiftc -DDISABLE_FOCUSED_EXAMPLES
  - label: "Danger"
    commands:
      - echo "--- Install Bundler"
      - gem install bundler
      - echo "--- Bundle Install"
      - bundle install
      - echo "+++ Run Danger"
      - bundle exec danger --verbose
  - label: "TSan Tests"
    commands:
      - echo "+++ Test"
      - bazel test --test_output=errors --build_tests_only --features=tsan --test_timeout=1000 //Tests/...
  - label: "Sourcery"
    commands:
      - echo "+++ Run Sourcery"
      - make --always-make sourcery
      - echo "+++ Diff Files"
      - git diff --quiet HEAD
  - label: "CocoaPods"
    env:
      DEVELOPER_DIR: "/Applications/Xcode-15.0.0.app"
    commands:
      - echo "bundle install"
      - bundle install --path vendor/bundle
      - echo "pod repo update"
      - bundle exec pod repo update
      - echo "pod lib lint"
      - bundle exec pod lib lint --verbose
