steps:
  - label: "Bazel"
    commands:
      - echo "+++ Build"
      - bazel build :swiftlint
      - echo "+++ Test"
      - bazel test --test_output=errors //Tests/...
  - label: "Danger"
    commands:
      - echo "--- Bundle Install"
      - bundle install
      - echo "+++ Run Danger"
      - bundle exec danger --verbose
  - label: "Analyze"
    commands:
      - echo "+++ Build With Bazel"
      - bazel build -c opt swiftlint
      - echo "+++ Build With SwiftPM"
      - swift build
      - echo "+++ Analyze"
      - bazel test -c opt --test_output=streamed --test_timeout=1800 --spawn_strategy=local --test_env=PROJECT_ROOT=$(bazel info workspace) analyze
  - label: "TSan"
    commands:
      - echo "+++ Test"
      - bazel test --xcode_version_config=//bazel:xcode_config --test_output=streamed --build_tests_only --features=tsan --test_timeout=600 //Tests/...
