steps:
  - label: "Bazel"
    env:
      DEVELOPER_DIR: /Applications/Xcode-13.4.1.app/Contents/Developer
    commands:
      - echo "+++ Build"
      - bazel build :swiftlint
      - echo "+++ Test"
      - bazel test --test_output=errors //Tests/...
  - label: "Danger"
    env:
      DEVELOPER_DIR: /Applications/Xcode-13.4.1.app/Contents/Developer
    commands:
      - echo "--- Bundle Install"
      - bundle install
      - echo "+++ Run Danger"
      - bundle exec danger --verbose
  - label: "Analyze"
    env:
      DEVELOPER_DIR: /Applications/Xcode-13.4.1.app/Contents/Developer
    commands:
      - echo "+++ Analyze"
      - make analyze
