steps:
  - label: "SwiftPM"
    env:
      DEVELOPER_DIR: /Applications/Xcode-15.0.0.app/Contents/Developer
    commands:
      - echo "+++ Test"
      - swift test --parallel -Xswiftc -DDISABLE_FOCUSED_EXAMPLES
  - label: "Sourcery"
    commands:
      - echo "+++ Run Sourcery"
      - make --always-make sourcery
      - echo "+++ Diff Files"
      - git diff --quiet HEAD
