name: Run Make Rule
description: Runs a specified Makefile rule
inputs:
  rule:
    description: The Makefile rule to run
    required: true
    default: build
runs:
  using: composite
  steps:
    - run: |
        awk '
          $0 ~ "${{ inputs.rule }}:" { in_rule = 1; next }
          in_rule && /^\t/ { print $0 }
          in_rule && !/^\t/ { in_rule = 0 }
        ' Makefile | while IFS= read -r command; do
          eval "$command"
        done
      shell: bash
