name: Bazel Linux Build
description: Common steps to build SwiftLint with Bazel on GitHub Linux runners
inputs:
  target:
    description: The Bazel target to build
    default: //:swiftlint
runs:
  using: composite
  steps:
    - name: Create ci.bazelrc file
      shell: bash
      run: echo "$CI_BAZELRC_FILE_CONTENT" | base64 -d > ci.bazelrc
      env:
        CI_BAZELRC_FILE_CONTENT: ${{ env.CI_BAZELRC_FILE_CONTENT }}
    - name: Apply patch
      shell: bash
      run: |
        git apply --ignore-whitespace .bcr/patches/no-warnings-as-errors.patch
        git update-index --assume-unchanged BUILD
    - name: Update environment
      shell: bash
      run: |
        echo "/usr/share/swift/usr/bin" >> $GITHUB_PATH
        echo "CC=clang" >> $GITHUB_ENV
    - name: Build SwiftLint with Bazel
      shell: bash
      run: bazel build --config release ${{ inputs.target }}
