name: Bazel Linux Build
description: Common steps to build SwiftLint with Bazel on GitHub Linux runners
inputs:
  target:
    description: The Bazel target to build
    default: //:swiftlint
runs:
  using: composite
  steps:
    - name: Create ci.bazelrc file
      shell: bash
      run: echo "$CI_BAZELRC_FILE_CONTENT" | base64 -d > ci.bazelrc
      env:
        CI_BAZELRC_FILE_CONTENT: ${{ env.CI_BAZELRC_FILE_CONTENT }}
    - name: Apply patch
      shell: bash
      run: git apply --ignore-whitespace .bcr/patches/no-warnings-as-errors.patch
    - name: Build SwiftLint with Bazel
      shell: bash
      run: |
        export PATH="/usr/share/swift/usr/bin:$PATH"
        bazel build --config release ${{ inputs.target }}
      env:
        CC: clang
