name: 'Bazel Linux Build'
description: 'Common steps to build SwiftLint with Bazel on GitHub Linux runners'
runs:
  using: 'composite'
  steps:
    - name: Add Swift to PATH
      run: export PATH="/usr/share/swift/usr/bin:$PATH"
    - name: Create ci.bazelrc file
      run: echo "$CI_BAZELRC_FILE_CONTENT" | base64 -d > ci.bazelrc
      env:
        CI_BAZELRC_FILE_CONTENT: ${{ env.CI_BAZELRC_FILE_CONTENT }}
    - name: Apply patch
      run: git apply --ignore-whitespace .bcr/patches/no-warnings-as-errors.patch
    - name: Build SwiftLint with Bazel
      run: bazel build --config release //:swiftlint
      env:
        CC: clang
