name: Docker Build
description: Common steps to build a Docker image for a specific platform
inputs:
  platform:
    description: Target platform (e.g., amd64, arm64)
    required: true
  token:
    description: GitHub token for authentication
    required: true

runs:
  using: composite
  steps:
    - name: Set lowercase repository name
      run: echo "REPOSITORY_LC=${REPOSITORY,,}" >> "$GITHUB_ENV"
      shell: bash
      env:
        REPOSITORY: ${{ github.repository }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
    - name: Login to GitHub registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
        registry: ghcr.io
    - name: Build and push by digest
      id: build
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: .
        platforms: linux/${{ inputs.platform }}
        outputs: >-
          type=image,
          name=ghcr.io/${{ env.REPOSITORY_LC }},
          push-by-digest=true,
          name-canonical=true,
          push=true
        cache-from: >-
          type=gha,
          scope=build-${{ inputs.platform }}
        cache-to: >-
          type=gha,
          mode=max,
          scope=build-${{ inputs.platform }}
    - name: Export digest
      shell: bash
      run: |
        mkdir -p /tmp/digests
        digest="${{ steps.build.outputs.digest }}"
        touch "/tmp/digests/${digest#sha256:}"
    - name: Upload digest
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: digests-${{ inputs.platform }}
        path: /tmp/digests/*
        if-no-files-found: error
        retention-days: 1
