#!/bin/bash

if [[ $BUILDKITE_BRANCH != 'main' ]]; then
  exit 0
fi

# TODO: Make this script compatible with Buildkite
exit 1

source_sha="$(git rev-parse HEAD)"
user="swiftlintbot@jpsim.com"
git config --global user.email "$user"
git config --global user.name "$user"
git clone git@github.com:realm/SwiftLint.git out

cd out
git checkout gh-pages
git rm -rf .
cd ..

cp -a docs/. out/.
cd out

git add -A
git commit -m "Automated deployment to GitHub Pages: ${source_sha}" --allow-empty

git push origin gh-pages
