struct LargeTupleRuleExamples {
    static let nonTriggeringExamples: [Example] = [
        "let foo: (Int, Int)\n",
        "let foo: (start: Int, end: Int)\n",
        "let foo: (Int, (Int, String))\n",
        "func foo() -> (Int, Int)\n",
        "func foo() -> (Int, Int) {}\n",
        "func foo(bar: String) -> (Int, Int)\n",
        "func foo(bar: String) -> (Int, Int) {}\n",
        "func foo() throws -> (Int, Int)\n",
        "func foo() throws -> (Int, Int) {}\n",
        "let foo: (Int, Int, Int) -> Void\n",
        "let foo: (Int, Int, Int) throws -> Void\n",
        "func foo(bar: (Int, String, Float) -> Void)\n",
        "func foo(bar: (Int, String, Float) throws -> Void)\n",
        "var completionHandler: ((_ data: Data?, _ resp: URLResponse?, _ e: NSError?) -> Void)!\n",
        "func getDictionaryAndInt() -> (Dictionary<Int, String>, Int)?\n",
        "func getGenericTypeAndInt() -> (Type<Int, String, Float>, Int)?\n",
        "func foo() async -> (Int, Int)\n",
        "func foo() async -> (Int, Int) {}\n",
        "func foo(bar: String) async -> (Int, Int)\n",
        "func foo(bar: String) async -> (Int, Int) {}\n",
        "func foo() async throws -> (Int, Int)\n",
        "func foo() async throws -> (Int, Int) {}\n",
        "let foo: (Int, Int, Int) async -> Void\n",
        "let foo: (Int, Int, Int) async throws -> Void\n",
        "func foo(bar: (Int, String, Float) async -> Void)\n",
        "func foo(bar: (Int, String, Float) async throws -> Void)\n",
        "func getDictionaryAndInt() async -> (Dictionary<Int, String>, Int)?\n",
        "func getGenericTypeAndInt() async -> (Type<Int, String, Float>, Int)?\n"
    ]

    static let triggeringExamples: [Example] = [
        "let foo: ↓(Int, Int, Int)\n",
        "let foo: ↓(start: Int, end: Int, value: String)\n",
        "let foo: (Int, ↓(Int, Int, Int))\n",
        "func foo(bar: ↓(Int, Int, Int))\n",
        "func foo() -> ↓(Int, Int, Int)\n",
        "func foo() -> ↓(Int, Int, Int) {}\n",
        "func foo(bar: String) -> ↓(Int, Int, Int)\n",
        "func foo(bar: String) -> ↓(Int, Int, Int) {}\n",
        "func foo() throws -> ↓(Int, Int, Int)\n",
        "func foo() throws -> ↓(Int, Int, Int) {}\n",
        "func foo() throws -> ↓(Int, ↓(String, String, String), Int) {}\n",
        "func getDictionaryAndInt() -> (Dictionary<Int, ↓(String, String, String)>, Int)?\n",
        "func foo(bar: ↓(Int, Int, Int)) async\n",
        "func foo() async -> ↓(Int, Int, Int)\n",
        "func foo() async -> ↓(Int, Int, Int) {}\n",
        "func foo(bar: String) async -> ↓(Int, Int, Int)\n",
        "func foo(bar: String) async -> ↓(Int, Int, Int) {}\n",
        "func foo() async throws -> ↓(Int, Int, Int)\n",
        "func foo() async throws -> ↓(Int, Int, Int) {}\n",
        "func foo() async throws -> ↓(Int, ↓(String, String, String), Int) {}\n",
        "func getDictionaryAndInt() async -> (Dictionary<Int, ↓(String, String, String)>, Int)?\n"
    ]
}
