name: Build

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  bazel_linux:
    name: Bazel ${{ matrix.bazel_version }}, Linux, Swift 6.3 # pre-installed
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - bazel_version: 7.6.1
          - bazel_version: 8.7.0
          - bazel_version: 9.1.1
    steps:
      - &checkout-step
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/bazel-linux
        name: Build SwiftLint with Bazel
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel_version }}
          CI_BAZELRC_FILE_CONTENT: ${{ secrets.CI_BAZELRC_FILE_CONTENT }}
      - name: Verify SourceKit dynamic loading behavior
        run: bash tools/verify-sourcekit-loading.sh bazel-bin/swiftlint .

  bazel_macos:
    name: Bazel, macOS 14, Xcode 16.2 # default
    runs-on: macos-14
    steps:
      - *checkout-step
      - name: Build SwiftLint with Bazel
        run: make --debug bazel_release
        env:
          DEVELOPER_DIR: /Applications/Xcode_16.2.app


  plugins_linux:
    name: SPM plugins, Linux, Swift ${{ matrix.version }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: swift:5.9-jammy
            version: "5.9"
          - image: swift:5.10-noble
            version: "5.10"
          - image: swift:6.0-noble
            version: "6.0"
          - image: swift:6.1-noble
            version: "6.1"
          - image: swift:6.2-noble
            version: "6.2"
          - image: swift:6.3-noble
            version: "6.3"
    container: ${{ matrix.image }}
    steps:
      - *checkout-step
      - name: Build plugins
        uses: ./.github/actions/run-make
        with:
          rule: spm_build_plugins
