name: pod lib lint

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

jobs:
  pod_lib_lint:
    name: pod lib lint
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app
    steps:
      - uses: actions/checkout@v2
      - run: bundle install --path vendor/bundle
      - run: bundle exec pod repo update
      - run: bundle exec pod lib lint --verbose
