name: Stale Issues

on:
  schedule:
    - cron: '0 0 15 * *'
  workflow_dispatch:

permissions:
  issues: write

jobs:
  close-stale-issues:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Mark or close stale issues
        run: |
          ./tools/stale-issues.rb ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
