name: Stale Issues

on:
  schedule:
    - cron: '0 0 15 * *'
  workflow_dispatch:

permissions:
  issues: write

jobs:
  close-stale-issues:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Mark or close stale issues
        run: |
          ./tools/stale-issues.rb ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
