name: TSan

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

jobs:
  tsan:
    name: TSan
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.1.app
    steps:
      - uses: actions/checkout@v2
      - run: swift run --sanitize=thread swiftlint lint --lenient
        name: Pre-cache SwiftLint Run
      - run: swift run --sanitize=thread swiftlint lint --lenient
        name: Post-cache SwiftLint Run
      - run: make test_tsan
        name: Test With TSan
